# 项目名称，必填字端
name: newtify
# 版本号，非必填
# 若需要将项目托管在pub.dev则该字段必填。
version: 1.2.3
# 项目描述，非必填
# 若需要将项目托管在pub.dev则该字段必填。
description:
   a new flutter module project

# 项目的第三方插件依赖，在这个标签中列出了该项目正常工作所需的每一个软件包与版本。以下通过实例详解该标签的详情
dependencies:
  http: ^0.12.0+4
  date_format: ^1.0.8

#配置
#3、配置dependencies
#4、运行pub get 获取远程库
#5、看文档引入库使用  
 

