List listData = [
           {
                "ads_type":"5",
                "brand_id":"",
                "category_id":"",
                "link":"http://zt.cjwsc.com/zt/all_page/20190610jidan/index.html",
                "pic":"https://static.cjwsc.com//image/93/c8/ef/93c8ef23bc7e1139e54de66090ddd2b5.jpg",
                "product_id":"",
                "store_id":"",
                "title":"血拼618"
            },
            {
                "ads_type":"5",
                "brand_id":"",
                "category_id":"",
                "link":"http://zt.cjwsc.com/zt/all_page/20190615kangbao/index.html",
                "pic":"https://static.cjwsc.com//image/58/4f/4e/584f4ea908341ee0664e60baa9170698.jpg",
                "product_id":"",
                "store_id":"",
                "title":"感恩圣典"
            },
            {
                "ads_type":"5",
                "brand_id":"",
                "category_id":"",
                "link":"http://zt.cjwsc.com/zt/all_page/20190615tcl/index.html",
                "pic":"https://static.cjwsc.com//image/6f/9c/4d/6f9c4d009ed7eb7c6332fb1b0904811d.jpg",
                "product_id":"",
                "store_id":"",
                "title":"畅销家电618"
            },
            {
                "ads_type":"5",
                "brand_id":"",
                "category_id":"",
                "link":"http://zt.cjwsc.com/zt/all_page/20190610jidan/index.html",
                "pic":"https://static.cjwsc.com//image/93/c8/ef/93c8ef23bc7e1139e54de66090ddd2b5.jpg",
                "product_id":"",
                "store_id":"",
                "title":"血拼618"
            },
            {
                "ads_type":"5",
                "brand_id":"",
                "category_id":"",
                "link":"http://zt.cjwsc.com/zt/all_page/20190615kangbao/index.html",
                "pic":"https://static.cjwsc.com//image/58/4f/4e/584f4ea908341ee0664e60baa9170698.jpg",
                "product_id":"",
                "store_id":"",
                "title":"感恩圣典"
            },
            {
                "ads_type":"5",
                "brand_id":"",
                "category_id":"",
                "link":"http://zt.cjwsc.com/zt/all_page/20190615tcl/index.html",
                "pic":"https://static.cjwsc.com//image/6f/9c/4d/6f9c4d009ed7eb7c6332fb1b0904811d.jpg",
                "product_id":"",
                "store_id":"",
                "title":"畅销家电618"
            },
            {
                "ads_type":"5",
                "brand_id":"",
                "category_id":"",
                "link":"http://zt.cjwsc.com/zt/all_page/20190610jidan/index.html",
                "pic":"https://static.cjwsc.com//image/93/c8/ef/93c8ef23bc7e1139e54de66090ddd2b5.jpg",
                "product_id":"",
                "store_id":"",
                "title":"血拼618"
            },
            {
                "ads_type":"5",
                "brand_id":"",
                "category_id":"",
                "link":"http://zt.cjwsc.com/zt/all_page/20190615kangbao/index.html",
                "pic":"https://static.cjwsc.com//image/58/4f/4e/584f4ea908341ee0664e60baa9170698.jpg",
                "product_id":"",
                "store_id":"",
                "title":"感恩圣典"
            },
            {
                "ads_type":"5",
                "brand_id":"",
                "category_id":"",
                "link":"http://zt.cjwsc.com/zt/all_page/20190615tcl/index.html",
                "pic":"https://static.cjwsc.com//image/6f/9c/4d/6f9c4d009ed7eb7c6332fb1b0904811d.jpg",
                "product_id":"",
                "store_id":"",
                "title":"畅销家电618"
            },
            {
                "ads_type":"5",
                "brand_id":"",
                "category_id":"",
                "link":"http://zt.cjwsc.com/zt/all_page/20190610jidan/index.html",
                "pic":"https://static.cjwsc.com//image/93/c8/ef/93c8ef23bc7e1139e54de66090ddd2b5.jpg",
                "product_id":"",
                "store_id":"",
                "title":"血拼618"
            },
            {
                "ads_type":"5",
                "brand_id":"",
                "category_id":"",
                "link":"http://zt.cjwsc.com/zt/all_page/20190615kangbao/index.html",
                "pic":"https://static.cjwsc.com//image/58/4f/4e/584f4ea908341ee0664e60baa9170698.jpg",
                "product_id":"",
                "store_id":"",
                "title":"感恩圣典"
            },
            {
                "ads_type":"5",
                "brand_id":"",
                "category_id":"",
                "link":"http://zt.cjwsc.com/zt/all_page/20190615tcl/index.html",
                "pic":"https://static.cjwsc.com//image/6f/9c/4d/6f9c4d009ed7eb7c6332fb1b0904811d.jpg",
                "product_id":"",
                "store_id":"",
                "title":"畅销家电618"
            },
            {
                "ads_type":"5",
                "brand_id":"",
                "category_id":"",
                "link":"http://zt.cjwsc.com/zt/all_page/20190610jidan/index.html",
                "pic":"https://static.cjwsc.com//image/93/c8/ef/93c8ef23bc7e1139e54de66090ddd2b5.jpg",
                "product_id":"",
                "store_id":"",
                "title":"血拼618"
            },
            {
                "ads_type":"5",
                "brand_id":"",
                "category_id":"",
                "link":"http://zt.cjwsc.com/zt/all_page/20190615kangbao/index.html",
                "pic":"https://static.cjwsc.com//image/58/4f/4e/584f4ea908341ee0664e60baa9170698.jpg",
                "product_id":"",
                "store_id":"",
                "title":"感恩圣典"
            },
            {
                "ads_type":"5",
                "brand_id":"",
                "category_id":"",
                "link":"http://zt.cjwsc.com/zt/all_page/20190615tcl/index.html",
                "pic":"https://static.cjwsc.com//image/6f/9c/4d/6f9c4d009ed7eb7c6332fb1b0904811d.jpg",
                "product_id":"",
                "store_id":"",
                "title":"畅销家电618"
            }

] ;